from social_net.auth.application.common.exceptions.base import ApplicationError


class UserNotFoundError(ApplicationError): # type: ignore[misc]
    ...
